// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NYA.MAP.LAYER_Adapter","status":true,"description":"无限图层显示系统","parameters":{}},
{"name":"NYA.MAP_Adapter","status":true,"description":"改变玩家切地图时的过渡效果","parameters":{}},
{"name":"NYA.EVENT.TRIGGER_Adapter","status":true,"description":"事件的触发范围","parameters":{}},
{"name":"NYA.ACHIEVES_Adapter","status":true,"description":"调用excel中的故事文案","parameters":{}},
{"name":"NYA.EVENT.AI_Adapter","status":true,"description":"事件的AI附加内容","parameters":{}},
{"name":"NYA.Utils","status":true,"description":"一些杂项功能","parameters":{}},
{"name":"NYA.LILY","status":true,"description":"莉莉亚的相关指令","parameters":{}},
{"name":"NYA.BOSS_ACHIEVES","status":true,"description":"BOSS评分","parameters":{}},
{"name":"NYA.AUDIO","status":true,"description":"音频相关","parameters":{}}
];
